### ISSUE TITLE
Adicionar Informações na página de perfil personagem

### ISSUE THREAD

**Issue by CarolinaSanches24** [CarolinaSanches24/desafio-RickAndMorty-SquadDorothy-Vaughan#10]
Na página de perfil do personagem, adicione as seguintes informações: 

- espécie
- gênero
- origem 
-  localização. 
- As informações de origem, localização e episódios em que o personagem aparece devem conter um link para a página de perfil da localização.

Link da Api Rick And Morty  :point_down: 

[Documentation](https://rickandmortyapi.com/documentation/#rest)

**Comment by anafbarreto** [comment]
Feito!
Rotas de localização e origem adicionadas.
